version: '3.8'

services:
  frontend:
    build:
      context: ./complete/frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: ./complete/backend
      dockerfile: Dockerfile
    ports:
      - "9002:9002"
    env_file:
      - ./complete/backend/.env

  flask:
    build:
      context: ./flask
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
